const providers = {
  android: [
    {
      name: 'cryptoservers',
      title: 'CryptoServers',
      logo: 'providers/cryptoservers.svg',
      website: 'https://cryptoservers.net',
      faq: 'https://myvpn.run/faq/setup/cryptoservers',
      oauthConfig: {
        client_id: 'wHZLfjVLK3VSwYEZpVycIfEs8aGTXnEKoCWJHHII',
        redirect_uri: 'https://myvpn-host.com/',
        scope: '*',
        authorize_url: 'https://cryptoservers.net/oauth/authorize',
        response_type: 'token',
      },
      oauthWindow: { width: 600, height: 540 },
    },
    {
      name: 'digitalocean',
      title: 'DigitalOcean',
      logo: 'providers/digitalocean.svg',
      website: 'https://www.digitalocean.com',
      faq: 'https://myvpn.run/faq/setup/digitalocean',
      oauthConfig: {
        client_id: 'a018284aebda94528eb1fdb00e5f53803590f3dd050a1da64a9e549e2eb1c309',
        redirect_uri: 'https://myvpn-host.com/',
        scope: 'read write',
        authorize_url: 'https://cloud.digitalocean.com/v1/oauth/authorize',
        response_type: 'token',
      },
      oauthWindow: { width: 760, height: 705 },
    },
    {
      name: 'linode',
      title: 'Linode',
      logo: 'providers/linode.svg',
      website: 'https://www.linode.com',
      faq: 'https://myvpn.run/faq/setup/linode',
      oauthConfig: {
        client_id: '608df50340fd04334ee9f04068786f86fc99a940210972e569c31e4300cdddb6',
        redirect_uri: 'https://myvpn-host.com/',
        scope: 'linodes:read_write,stackscripts:read_write',
        authorize_url: 'https://login.linode.com/oauth/authorize',
        response_type: 'token',
      },
      oauthWindow: { width: 600, height: 710 },
    },
  ],

  desktop: [
    {
      name: 'cryptoservers',
      title: 'CryptoServers',
      logo: 'providers/cryptoservers.svg',
      website: 'https://cryptoservers.net',
      faq: 'https://myvpn.run/faq/setup/cryptoservers',
      oauthConfig: {
        client_id: '173',
        redirect_uri: 'http://localhost',
        scope: '*',
        authorize_url: 'https://cryptoservers.net/oauth/authorize',
        response_type: 'token',
      },
      oauthWindow: { width: 600, height: 540 },
    },
    {
      name: 'digitalocean',
      title: 'DigitalOcean',
      logo: 'providers/digitalocean.svg',
      website: 'https://www.digitalocean.com',
      faq: 'https://myvpn.run/faq/setup/digitalocean',
      oauthConfig: {
        client_id: 'a018284aebda94528eb1fdb00e5f53803590f3dd050a1da64a9e549e2eb1c309',
        redirect_uri: 'https://localhost/',
        scope: 'read write',
        authorize_url: 'https://cloud.digitalocean.com/v1/oauth/authorize',
        response_type: 'token',
      },
      oauthWindow: { width: 760, height: 705 },
    },
    {
      name: 'linode',
      title: 'Linode',
      logo: 'providers/linode.svg',
      website: 'https://www.linode.com',
      faq: 'https://myvpn.run/faq/setup/linode',
      oauthConfig: {
        client_id: '839b0a3d0ab64f6c8c2d',
        redirect_uri: 'https://localhost/',
        scope: 'linodes:read_write,stackscripts:read_write',
        authorize_url: 'https://login.linode.com/oauth/authorize',
        response_type: 'token',
      },
      oauthWindow: { width: 600, height: 710 },
    },
    {
      name: 'hetznerCloud',
      title: 'Hetzner Cloud',
      logo: 'providers/hetzner-cloud.svg',
      website: 'https://www.hetzner.com/cloud',
      faq: 'https://myvpn.run/faq/setup/hetznerCloud',
      viaKey: true,
    },
    {
      name: 'custom',
      title: 'Other Server',
      logo: 'providers/custom.svg',
    },
  ],

  web: [
    {
      name: 'cryptoservers',
      title: 'CryptoServers',
      logo: 'providers/cryptoservers.svg',
      website: 'https://cryptoservers.net',
      faq: 'https://myvpn.run/faq/setup/cryptoservers',
      oauthConfig: {
        client_id: '199',
        redirect_uri: 'https://tool.myvpn.run',
        scope: '*',
        authorize_url: 'https://cryptoservers.net/oauth/authorize',
        response_type: 'token',
      },
      oauthWindow: { width: 600, height: 540 },
    },
    {
      name: 'digitalocean',
      title: 'DigitalOcean',
      logo: 'providers/digitalocean.svg',
      website: 'https://www.digitalocean.com',
      faq: 'https://myvpn.run/faq/setup/digitalocean',
      oauthConfig: {
        client_id: '72deece066d4413e9c776189616d340ed0997c3f108425b1d19dc2194f8e2393',
        redirect_uri: 'https://tool.myvpn.run',
        scope: 'read write',
        authorize_url: 'https://cloud.digitalocean.com/v1/oauth/authorize',
        response_type: 'token',
      },
      oauthWindow: { width: 760, height: 705 },
    },
    {
      name: 'linode',
      title: 'Linode',
      logo: 'providers/linode.svg',
      website: 'https://www.linode.com',
      faq: 'https://myvpn.run/faq/setup/linode',
      oauthConfig: {
        client_id: '434a211accf5a24afeef',
        redirect_uri: 'https://tool.myvpn.run',
        scope: 'linodes:read_write,stackscripts:read_write',
        authorize_url: 'https://login.linode.com/oauth/authorize',
        response_type: 'token',
      },
      oauthWindow: { width: 600, height: 710 },
    },
    {
      name: 'hetznerCloud',
      title: 'Hetzner Cloud',
      logo: 'providers/hetzner-cloud.svg',
      website: 'https://www.hetzner.com/cloud',
      faq: 'https://myvpn.run/faq/setup/hetznerCloud',
      viaKey: true,
    }
  ],
}

export default providers
